version: "3.8"

services:
  web:
    build:
      context: .
      target: builder
    command: sh -c 'yarn install && yarn run dev' #yarn install to ensure that binaries are built for container
    ports:
      - 5173:5173
    volumes:
      - .:/src

