version: "3.8"

services:
  web:
    environment:
      PUBLIC_AI_SERVICE_URL: 'http://127.0.0.1:7878'
    build:
      context: .
      target: builder
    command: sh -c 'yarn install && yarn run dev' #yarn install to ensure that binaries are built for container
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - node_modules:/app/node_modules # anonymous node_modules volumne to ensure that node_modules binaries are built in and used from the container and not from the local machine

volumes:
  node_modules:

